version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - 3.4.1
    - 3.4.2
    - 3.4.6
    - 3.4.7
  - dependency-name: pip-tools
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: pycryptodomex
    versions:
    - 3.10.1
  - dependency-name: pycryptodome
    versions:
    - 3.10.1
