dist: bionic

language: python

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-pycrypto,py27-pycryptodome,py27-pycryptodomex,py27-cryptography
    - python: 3.7
      env: TOXENV=py37-pycrypto,py37-pycryptodome,py37-pycryptodomex,py37-cryptography
    - python: 3.8
      env: TOXENV=py38-pycrypto,py38-pycryptodome,py38-pycryptodomex,py38-cryptography
    - python: pypy3
      env: TOXENV=pypy3-pycrypto,pypy3-pycryptodome,pypy3-pycryptodomex,pypy3-cryptography
    - python: 3.8
      env: TOXENV=lint,docs
      install:
        - pip install tox
      script:
        - tox

install:
    - pip install tox coveralls

script:
    - tox
    - coveralls
