dist: bionic

language: python

addons:
  apt:
    packages:
      - libgmp-dev

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-pycrypto,py27-pycryptodome,py27-pycryptodomex,py27-cryptography
    - python: 3.7
      env: TOXENV=py37-pycrypto,py37-pycryptodome,py37-pycryptodomex,py37-cryptography
    - python: 3.8
      env: TOXENV=py38-pycrypto,py38-pycryptodome,py38-pycryptodomex,py38-cryptography
    - python: 3.8
      env: TOXENV=docs

install:
    - pip install tox

script:
    - tox
